#input parameters
intensity       =       25e10 # LEIR_Pb: charges/54(/2) 
bunchLength_ns =        330 #4 sigma in ns
# bunchLength_m	=	    10 #1 sigma in m
emittance_x     =       1.2e-6
emittance_y     =       1.2e-6
dpp_rms         =       0.5e-3
# ro            =       # classical radius : default proton change for ions accordingly # Pb LEIR,PS: 2.16775246387e-17 # SPS_Pb: 4.9978e-17 
# bF            =       # None for Gaussian # 1 for coasting
Qh		=  4.4   # to estimate detuning and plot
Qv		=  4.45   # to estimate detuning and plot
plot_range  =   [[3.9,4.5]],[[3.9,4.5]]   # range in Qh & Qv for the plot
plot_order  =   4 # order of resonances to plot
periodicity =   16  # periodicity of ring for the colorcode of the plot
figure		=	'figure.png'
twiss_file  =   'twiss_files/twiss_PSB'
# harmonic  =   1
# b         =  # relativistic beta  :  if desired energy different than in twiss file # PS_Pb : 0.3720 
# g         =  # relativistic gamma :  if desired energy different than in twiss file # PS_Pb : 1.0773 PS_Pb 
